name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', 'truffleruby', 'jruby' ]
        faraday: [ '~> 0.17.3', '~> 1.0', '~> 2.0' ]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        continue-on-error: ${{ contains(fromJson('["truffleruby", "jruby"]'), matrix.ruby) }}
        run: bundle exec rake
